---
AllCops:
  Exclude:
    - 'build/**/*'

Metrics/LineLength:
  Max: 118

Metrics/MethodLength:
  Enabled: false

# Ruby 1.8 requirement
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 19
